[package]
name = "gist-web"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq      = { version = "2", default-features = false, features = ["rustls"] }
scraper   = "0.20"
url       = "2"
gist-core  = { path = "../gist-core" }
gist-model = { path = "../gist-model" }
thiserror = { workspace = true }
