name: core-quality
on:
  pull_request:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87  # stable
      - uses: EmbarkStudios/cargo-deny-action@34899fc28e28a96b4e8215ecdfdee2e2dbde5706  # v1
      - run: cargo audit
